name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm i --no-progress --no-optional --no-audit --ignore-scripts
      - run: npm t
    #- run: npm publish
    #  env:
    #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    #- uses: actions/setup-node@v2
    #  with:
    #    registry-url: 'https://npm.pkg.github.com'
    #- run: npm publish
    #  env:
    #    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
